name: 'actions-code-deploy'
inputs:
  project-file:
    required: true
  output-directory:
    required: true
  build-configuration:
    required: true
runs:
  using: "composite"
  steps:
      - run: dotnet restore ${{inputs.project-file}} --packages ../../packages --no-cache --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/grocerkey-feed/auth/${{secrets.MYGET_TOKEN}}/api/v3/index.json
        shell: powershell       
      - run: msbuild.exe  ${{inputs.project-file}} /p:OutDir= ${{inputs.output-directory}} /p:Configuration= ${{inputs.build-configuration}}
        shell: powershell
