name: 'actions-code-deploy'
inputs:
  project-file:
    required: true
  output-directory:
    required: true
  build-configuration:
    required: true
  github-creds:
    required: true
    
runs:
  using: "composite"
  steps:
      - run: dotnet nuget add source --username suleman-ppup --password ${{ inputs.github-creds }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GrocerKey/index.json"
        shell: powershell
      - run: dotnet restore ${{inputs.project-file}} --packages ../../packages --no-cache --source https://api.nuget.org/v3/index.json --source https://nuget.pkg.github.com/GrocerKey/index.json
        shell: powershell
      - run: echo "msbuild.exe ${{inputs.project-file}} /p:OutDir= ${{inputs.output-directory}} /p:Configuration= ${{inputs.build-configuration}}"
        shell: powershell
      - run: msbuild.exe "${{inputs.project-file}}" /p:OutDir="${{inputs.output-directory}}" /p:Configuration=${{inputs.build-configuration}}
        shell: powershell
